### PR TITLE
Adds gitter badge.

### PR DESCRIPTION
**Pull request by jcchavezs**
This PR adds the gitter badge

### CODE REVIEW

**Comment by felixfbecker** [comment]
I thought opentracing currently doesn't have dedicated channels per implementations (even though I think it should)?

**Comment by jcchavezs** [comment]
They just created that. Check https://gitter.im/opentracing/opentracing-php

**Comment by beberlei** [comment]
I think its just because we talk too much during the initial implementation, i guess this will become more quite at some point, so that we don't need the opentracing-php channel anymore, or?

**Comment by jcchavezs** [comment]
Makes sense.

**Pull request closed without merging**
